platform :ios, '13.0'
use_frameworks!

target 'SwiftUI_Jike' do

  pod 'Kingfisher', '~> 6.0'
  pod 'Alamofire', '~> 5.4.3'
  pod 'SwiftyJSON', '~> 5.0.1'
  # 瀑布流
  # pod 'WaterfallGrid', '~> 1.0.0'
  # pod 'ASCollectionView-SwiftUI', '~> 1.3'
  # 弹窗
  # pod 'ExytePopupView'
  
  
  # 参考1：https://github.com/quanghainguyen93/twitter-swiftui-clone
  # 参数2 Combine: https://zhuanlan.zhihu.com/p/346149814
  # 上下拉刷新：https://github.com/wxxsw/Refresh
  # GeekMadeBySwiftUI: https://github.com/JQHxx/GeekMadeBySwiftUI

end
