platform :ios, '13.0'
use_frameworks!

target 'SwiftUI_Jike' do

  # Combine
  pod 'Kingfisher', '~> 6.0'
  pod 'Alamofire', '~> 5.4.3'
  pod 'SwiftyJSON', '~> 5.0.1'
  
  
  # 参考1：https://github.com/quanghainguyen93/twitter-swiftui-clone

end
